# Generated by Django 5.2.12 on 2026-04-03 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('tip', 'Tip'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('cycle', 'Cycle Pattern'), ('pain', 'Pain Pattern'), ('mood', 'Mood Pattern'), ('flow', 'Flow Pattern'), ('lifestyle', 'Lifestyle'), ('risk', 'Health Risk')], default='cycle', max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('diet', 'Diet'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('productivity', 'Productivity'), ('selfcare', 'Self Care'), ('general', 'General')], default='general', max_length=15)),
                ('phase', models.CharField(blank=True, default='', max_length=15)),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
