# Generated by Django 5.2.12 on 2026-04-03 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_status', models.CharField(choices=[('none', 'No Period'), ('started', 'Period Started'), ('ongoing', 'Period Ongoing'), ('ended', 'Period Ended')], default='none', max_length=10)),
                ('pain_level', models.IntegerField(default=0, help_text='Pain level 0-5')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('low', 'Low'), ('irritated', 'Irritated'), ('anxious', 'Anxious'), ('sad', 'Sad')], default='calm', max_length=15)),
                ('flow_intensity', models.CharField(choices=[('none', 'None'), ('spotting', 'Spotting'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='none', max_length=10)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Hours of sleep', null=True)),
                ('stress_level', models.IntegerField(default=0, help_text='Stress level 0-5')),
                ('exercise_minutes', models.IntegerField(default=0, help_text='Minutes of exercise')),
                ('water_intake', models.IntegerField(default=0, help_text='Glasses of water')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cramps', 'Cramps'), ('headache', 'Headache'), ('bloating', 'Bloating'), ('fatigue', 'Fatigue'), ('nausea', 'Nausea'), ('breast_tenderness', 'Breast Tenderness'), ('back_pain', 'Back Pain'), ('acne', 'Acne'), ('cravings', 'Cravings'), ('insomnia', 'Insomnia'), ('dizziness', 'Dizziness'), ('mood_swings', 'Mood Swings'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField(default=1, help_text='Severity 1-5')),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='tracker.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='CycleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(blank=True, help_text='Days from this period start to next period start', null=True)),
                ('period_length', models.IntegerField(blank=True, help_text='Days of active bleeding', null=True)),
                ('is_predicted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'start_date')},
            },
        ),
    ]
